[package]
name = "kaspa-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
futures-util.workspace = true
wasm-bindgen.workspace = true
log.workspace = true
cfg-if.workspace = true
thiserror.workspace = true
env_logger = "0.10"
workflow-log.workspace = true
log4rs = "1.2.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["rt", "macros", "rt-multi-thread"] }
ctrlc = "3.2"
intertrait = "0.2"
num_cpus.workspace = true
